modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU-AGPL-3.0-only"
[[mods]]
modId = "stntr"
version = "${file.jarVersion}"
displayName = "StabilizeAndTransform"
authors = "Tapio"
description = ""
